### ISSUE TITLE
Build error: Cannot open include file: 'unistd.h': No such file or directory

### ISSUE THREAD

**Issue by Sparronator9999** [xenia-canary/xenia-canary#727]
### Validation

- [x] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [x] The Xenia build used is from a Canary branch. (not UWP/MLBS/AlexVS/master/pull requests, etc)
- [x] This issue isn't for tech support (help with Xenia).
- [x] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [x] I've checked if this issue hasn't already been reported.
- [x] My device meets the minimum requirements: https://github.com/xenia-canary/xenia-canary/wiki/Quickstart#system-requirements
- [x] (If building) I have read the building doc: https://github.com/xenia-canary/xenia-canary/blob/master/docs/building.md

### Describe what's going wrong

When trying to build Xenia using `xb build` (after running `xb setup` first), the compiler outputs the following error several times during the build (see attached log for full output):

```
C:\xenia-canary\third_party\zlib-ng\zconf-ng.h(136,1): error C1083: Cannot open include file: 'unistd.h': No such file
or directory [C:\xenia-canary\build\zlib-ng.vcxproj]
```

followed by a build failure after a few minutes of compiling.

Attempted to build using latest SDK (v10.0.26100.4654) on Windows 10. Hardware shouldn't matter for build purposes, but still meets requirements (Intel Core i7-11800H CPU + NVIDIA GTX 1650 Max-Q GPU + 2x8GB DDR4-3200 RAM).

### Describe what should happen

Xenia should build successfully, even with no code changes.

### If applicable, provide a callstack here, especially for crashes

N/A

### If applicable, upload a logfile and link it here

[Command Prompt output from latest build attempt](https://github.com/user-attachments/files/22549785/build.txt)

**Comment by Margen67** [comment]
Did you follow the [building instructions](https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/docs/building.md) and check this in the Visual Studio installer? 

<img width="425" height="118" alt="Image" src="https://github.com/user-attachments/assets/d986652f-c062-4607-a453-85ab9e77e911" />

**Comment by Sparronator9999** [comment]
> Did you follow the [building instructions](https://github.com/xenia-canary/xenia-canary/blob/canary_experimental/docs/building.md) and check this in the Visual Studio installer?

Yes.

<img width="416" height="537" alt="Image" src="https://github.com/user-attachments/assets/677eda53-fbed-48cc-8eca-aa9611b18e2c" />

(there are no checked items after what's shown in this screenshot for this workload)

**Comment by Sparronator9999** [comment]
Okay, here's a weird one. I tried downgrading my Windows SDK to 10.0.22621.0, then basically started compiling from scratch (including deleting and re-cloning the Xenia repository... not like I had any meaningful changes), and noticed this output during `xb setup`:

```
-- Looking for unistd.h - found
```

(this probably also appeared when using latest WinSDK, but didn't save the output then...)

Yet the build still fails while trying to build `zlib-ng` (same error as the original one):

```
C:\xenia-canary\third_party\zlib-ng\zconf-ng.h(136,1): error C1083: Cannot open include file: 'unistd.h': No such file
or directory [C:\xenia-canary\build\zlib-ng.vcxproj]
```

**Comment by Sparronator9999** [comment]
I decided to try building Xenia again today, and it finished compiling successfully today for some reason. Maybe there was some weird dependency issue that resolved itself, maybe some bug was fixed between me first opening this issue and today, or maybe it was because my computer was using [MSYS2](https://www.msys2.org/) Python for some reason (which I discovered a few weeks ago during an assignment). Either way, I guess this issue is no longer needed.
